<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CAMS.Application\CAMS.Application.csproj" />
    <ProjectReference Include="..\ThirdParty\Futronic\ftrSDKHelper\ftrSDKHelper.vcxproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Futronic\x64\" />
  </ItemGroup>
	<ItemGroup>
		<None Update="Futronic\x64\FTRAPI.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<TargetPath>FTRAPI.dll</TargetPath>
		</None>
		<None Update="Futronic\x64\ftrScanAPI.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<TargetPath>ftrScanAPI.dll</TargetPath>
		</None>
	</ItemGroup>
</Project>